### ISSUE TITLE
Build configuration is too large

### ISSUE THREAD

**Issue by nickoneill** [nickytonline/ts-preact-starter#172]
Thanks for this great starter, it's nice to have all the components set up together (though I couldn't get storyboard running with the default config).

One note: by default the js file that `webpack` generates is ~900kb. It warns you that it's defaulting to production mode but that doesn't change the webpack config behavior which is looknig for a command line argument. It's shipping all of hot reloading with the production js.

I adjusted the build command to `"build": "webpack --mode=production",` and the js is now a tidy 25kb.

**Comment by nickytonline** [comment]
Thanks for mentioning this. I whipped it up pretty quickly a couple of years ago. What would be good is to have it set up for development and production mode. This is generally pretty easy to setup in webpack. See https://webpack.js.org/configuration/mode/.

If you’re up for creating a PR that’d be awesome as it’d help others too.

Thanks again and enjoy the weekend!

**Comment by nickytonline** [comment]
Fixed by #173
